name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python tk numpy 
    - name: build with pyinstaller
      run: |
        cd gui
        pyinstaller .\gui\quiz.py -n foobar
    - uses: actions/upload-artifact@v2
      with:
        name: python-exe
        path: dist\foobar\