name: PyInstaller

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python tk numpy requests 
    - name: build with pyinstaller
      run: |
        pyinstaller .\gui\quiz.py -n quiz -F -w -i .\gui\favicon.ico
    - uses: actions/upload-artifact@v2
      with:
        name: python-exe
        path: dist\quiz.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist\quiz.exe
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true