name: PyInstaller

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python tk numpy requests 
    - name: build with pyinstaller
      run: |
        cd gui
        pyinstaller quiz.py -n quiz-windows -F  -i favicon.ico
    - uses: actions/upload-artifact@v2
      with:
        name: quiz-windows-exe
        path: .\gui\dist\quiz-windows.exe
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .\gui\dist\quiz-windows.exe
        tag: Automated Builds 
        overwrite: true
        file_glob: true

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: texam-ecajmer-hackathon
        SLACK_USERNAME: GHActions
        SLACK_ICON: favicon.ico
        SLACK_MESSAGE: 'New Release :rocket:'
        SLACK_TITLE: Completed build and release
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}